name: bluetooth_ble
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_blue_plus: 1.15.0
  shared_preferences: ^2.2.2  # Para guardar los límites
  flutter_local_notifications: ^17.0.0 # Para las alertas push

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
